apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-feed
  name: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - image: gonbewilson/udagram-api-feed
        name: backend-feed
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"       
        envFrom:
          - configMapRef:
              name: env-config
          - secretRef:
              name: env-secret
        ports:
        - containerPort: 8100
      restartPolicy: Always
